
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  my_new_project:
    # Applies to all files under models/example/
    example:
      materialized: view

seeds:
  +quote_columns: true
  CO-EST2022-POP-36:
    +column_types:
      Area: varchar
      Base_Estimate: bigint
      y2020: bigint
      y2021: bigint
      y2022: bigint

  COVID_19_Nursing_Home_Data_08_06_2023:
    +column_types:
      week_ending: timestamp_tz
      federal_provider_number: varchar
      provider_name: varchar
      provider_address: varchar
      provider_city: varchar
      provider_state: varchar
      provider_zip_code: varchar
      provider_phone_number: varchar
      county: varchar
      submitted_data: varchar
      passed_quality_assurance_check: varchar
      residents_weekly_confirmed_covid19: int
      residents_total_confirmed_covid19: int
      residents_weekly_all_deaths: int
      residents_total_all_deaths: int
      residents_weekly_covid19_deaths: int
      residents_total_covid19_deaths: int
      number_of_all_beds: int
      total_number_of_occupied_beds: int
      residents_hospitalizations_with_confirmed_covid19: int
      residents_hospitalizations_with_confirmed_covid19_and_up_to_date_with_vaccines: int
      staff_weekly_confirmed_covid19: int
      staff_total_confirmed_covid19: int
      weekly_resident_confirmed_covid19_cases_per_1000_residents: decimal(15,2)
      weekly_resident_covid19_deaths_per_1000: decimal(15,2)
      total_resident_confirmed_covid19_cases_per_1000_residents: decimal(15,2)
      total_resident_covid19_deaths_per_1000_residents: decimal(15,2)
      num_residents_up_to_date_on_covid19_vaccine_14d_or_more_before_positive_test: int
      num_residents_staying_in_facility_for_more_than_one_day_this_week: int
      num_healthcare_personnel_eligible_to_work_in_facility_for_at_least_1day_this_week: int
      num_all_healthcare_personnel_eligible_to_work_who_received_covid19_vaccine: int
      recent_percentage_healthcare_personnel_w_vaccine,percentage_current_healthcare_personnel_wtih_vaccine: decimal(15,2)
      num_residents_staying_in_facility_at_least_one_day_this_week_with_covid_vaccines: int
      recent_percentage_of_residents_up_to_date_with_covid19_vaccines: decimal(15,2)
      percentage_current_residents_up_to_date_with_covid_vaccines: decimal(15,2)
      num_healthcare_personnel_eligible_to_work_up_to_date_with_covid_vaccines: int
      recent_percentage_healthcare_personnel_up_to_date_with_covid_vaccines: decimal(15,2)
      percentage_current_healthcare_personnel_up_to_date_w_covid_vaccines: decimal(15,2)